package com.sanchit.passportphoto;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.FaceDetector;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;
public class MainActivity extends Activity{
 private ImageView preview;private Bitmap original,result;private SeekBar brightness,smooth;private static final int PICK=10,CAMERA=11,CAM_PERMISSION=12;
 @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();}
 private TextView text(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setPadding(16,10,16,10);return t;}private Button button(String s){Button b=new Button(this);b.setText(s);return b;}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);TextView title=text("Sanchit Passport Photo V1.0.1",24);title.setGravity(Gravity.CENTER);root.addView(title);root.addView(text("Face-aware Crop • Edge-safe Background • बिना AI",14));preview=new ImageView(this);preview.setBackgroundColor(Color.rgb(230,230,230));preview.setScaleType(ImageView.ScaleType.FIT_CENTER);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));LinearLayout source=new LinearLayout(this);Button camera=button("📷 कैमरा");Button pick=button("🖼 फोटो चुनें");source.addView(camera,new LinearLayout.LayoutParams(0,-2,1));source.addView(pick,new LinearLayout.LayoutParams(0,-2,1));root.addView(source);camera.setOnClickListener(v->openCamera());pick.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI),PICK));root.addView(text("Fairness / Brightness",14));brightness=new SeekBar(this);brightness.setMax(50);brightness.setProgress(12);root.addView(brightness);root.addView(text("Smooth",14));smooth=new SeekBar(this);smooth.setMax(3);smooth.setProgress(1);root.addView(smooth);LinearLayout row=new LinearLayout(this);Button process=button("फिर से PROCESS");Button reset=button("RESET");row.addView(process,new LinearLayout.LayoutParams(0,-2,1));row.addView(reset,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);process.setOnClickListener(v->process());reset.setOnClickListener(v->reset());Button save=button("फोटो सेव करें");root.addView(save);save.setOnClickListener(v->save());setContentView(root);}
 private void openCamera(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.CAMERA")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.CAMERA"},CAM_PERMISSION);return;}Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);if(i.resolveActivity(getPackageManager())!=null)startActivityForResult(i,CAMERA);else toast("Camera उपलब्ध नहीं है");}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==CAM_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)openCamera();else if(r==CAM_PERMISSION)toast("Camera permission जरूरी है");}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);try{if(c!=RESULT_OK)return;if(r==PICK&&d!=null){original=MediaStore.Images.Media.getBitmap(getContentResolver(),d.getData());auto();}else if(r==CAMERA&&d!=null&&d.getExtras()!=null){Object o=d.getExtras().get("data");if(o instanceof Bitmap){original=(Bitmap)o;auto();}}}catch(Exception e){toast("Photo error: "+e.getMessage());}}
 private void auto(){brightness.setProgress(12);smooth.setProgress(1);process();}
 private void reset(){result=null;original=null;preview.setImageDrawable(null);brightness.setProgress(12);smooth.setProgress(1);toast("Reset हो गया — नई फोटो चुनें");}
 private void process(){if(original==null){toast("पहले फोटो लें या चुनें");return;}Bitmap crop=smartCrop(original);int w=700,h=900;Bitmap src=Bitmap.createScaledBitmap(crop,w,h,true);int[] p=new int[w*h];src.getPixels(p,0,w,0,0,w,h);boolean[] bgMask=edgeBackgroundMask(p,w,h);int add=brightness.getProgress();for(int i=0;i<p.length;i++){if(bgMask[i]){p[i]=Color.rgb(74,144,194);continue;}int c=p[i],r=Color.red(c),g=Color.green(c),b=Color.blue(c);r=clamp((int)(r*1.018f)+add);g=clamp((int)(g*1.018f)+add);b=clamp((int)(b*1.012f)+add);p[i]=Color.rgb(r,g,b);}Bitmap out=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);out.setPixels(p,0,w,0,0,w,h);if(smooth.getProgress()>0)out=softSmooth(out,smooth.getProgress());result=out;preview.setImageBitmap(result);toast("V1.0.1 Auto Process तैयार");}
 private boolean[] edgeBackgroundMask(int[] p,int w,int h){boolean[] seen=new boolean[p.length],mask=new boolean[p.length];int sample=18,sr=0,sg=0,sb=0,n=0;for(int y=0;y<sample;y++)for(int x=0;x<sample;x++){int[] ids={y*w+x,y*w+(w-1-x),(h-1-y)*w+x,(h-1-y)*w+(w-1-x)};for(int id:ids){int c=p[id];sr+=Color.red(c);sg+=Color.green(c);sb+=Color.blue(c);n++;}}final int rr=sr/n,gg=sg/n,bb=sb/n;ArrayDeque<Integer> q=new ArrayDeque<>();for(int x=0;x<w;x++){seed(q,seen,p,x,w,h,rr,gg,bb);seed(q,seen,p,(h-1)*w+x,w,h,rr,gg,bb);}for(int y=0;y<h;y++){seed(q,seen,p,y*w,w,h,rr,gg,bb);seed(q,seen,p,y*w+w-1,w,h,rr,gg,bb);}int[] dx={1,-1,0,0},dy={0,0,1,-1};while(!q.isEmpty()){int id=q.removeFirst();mask[id]=true;int x=id%w,y=id/w;for(int k=0;k<4;k++){int nx=x+dx[k],ny=y+dy[k];if(nx<0||ny<0||nx>=w||ny>=h)continue;int ni=ny*w+nx;if(!seen[ni]&&isBackgroundLike(p[ni],rr,gg,bb)){seen[ni]=true;q.add(ni);}}}return mask;}
 private void seed(ArrayDeque<Integer> q,boolean[] seen,int[] p,int id,int w,int h,int r,int g,int b){if(id>=0&&id<p.length&&!seen[id]&&isBackgroundLike(p[id],r,g,b)){seen[id]=true;q.add(id);}}
 private boolean isBackgroundLike(int c,int r,int g,int b){int cr=Color.red(c),cg=Color.green(c),cb=Color.blue(c);int dr=cr-r,dg=cg-g,db=cb-b;double d=Math.sqrt(dr*dr+dg*dg+db*db);boolean near=d<43;boolean neutralBright=cr>225&&cg>225&&cb>225&&Math.max(cr,Math.max(cg,cb))-Math.min(cr,Math.min(cg,cb))<22;boolean green=cg>95&&cg>cr*1.28&&cg>cb*1.20;return near||neutralBright||green;}
 private int clamp(int v){return Math.max(0,Math.min(255,v));}
 private Bitmap softSmooth(Bitmap s,int level){int w=s.getWidth(),h=s.getHeight();int[] a=new int[w*h],o=new int[w*h];s.getPixels(a,0,w,0,0,w,h);System.arraycopy(a,0,o,0,a.length);float blend=Math.min(.34f,.12f*level);for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int id=y*w+x,c=a[id],r=Color.red(c),g=Color.green(c),b=Color.blue(c);if(b>r*1.20&&b>g*.92)continue;int ar=0,ag=0,ab=0;for(int yy=-1;yy<=1;yy++)for(int xx=-1;xx<=1;xx++){int z=a[(y+yy)*w+x+xx];ar+=Color.red(z);ag+=Color.green(z);ab+=Color.blue(z);}ar/=9;ag/=9;ab/=9;o[id]=Color.rgb(clamp((int)(r*(1-blend)+ar*blend)),clamp((int)(g*(1-blend)+ag*blend)),clamp((int)(b*(1-blend)+ab*blend)));}Bitmap d=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);d.setPixels(o,0,w,0,0,w,h);return d;}
 private Bitmap smartCrop(Bitmap b){try{int ow=b.getWidth(),oh=b.getHeight();int dw=Math.min(1000,ow);float scale=(float)dw/ow;int dh=Math.max(2,(int)(oh*scale));if((dw&1)==1)dw--;Bitmap small=Bitmap.createScaledBitmap(b,dw,dh,true).copy(Bitmap.Config.RGB_565,false);FaceDetector fd=new FaceDetector(small.getWidth(),small.getHeight(),1);FaceDetector.Face[] fs=new FaceDetector.Face[1];if(fd.findFaces(small,fs)>0&&fs[0]!=null){PointF m=new PointF();fs[0].getMidPoint(m);float inv=(float)ow/small.getWidth(),cx=m.x*inv,eyesY=m.y*inv,eye=fs[0].eyesDistance()*inv;float cw=Math.max(eye*5.5f,ow*.36f);cw=Math.min(cw,ow);float ch=cw*9f/7f;if(ch>oh){ch=oh;cw=ch*7f/9f;}float left=cx-cw/2f,top=eyesY-ch*.40f;left=Math.max(0,Math.min(left,ow-cw));top=Math.max(0,Math.min(top,oh-ch));return Bitmap.createBitmap(b,Math.round(left),Math.round(top),Math.round(cw),Math.round(ch));}}catch(Exception ignored){}return crop79(b);}
 private Bitmap crop79(Bitmap b){int w=b.getWidth(),h=b.getHeight();float t=7f/9f;int nw=w,nh=h;if((float)w/h>t)nw=(int)(h*t);else nh=(int)(w/t);return Bitmap.createBitmap(b,(w-nw)/2,(h-nh)/2,nw,nh);}
 private void save(){if(result==null){toast("पहले फोटो तैयार करें");return;}try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"Sanchit_Passport_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Sanchit Passport Photo");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);OutputStream os=getContentResolver().openOutputStream(u);result.compress(Bitmap.CompressFormat.JPEG,97,os);os.close();toast("फोटो सेव हो गई");}catch(Exception e){toast("Save error: "+e.getMessage());}}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}