package com.sanchit.passportphoto;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.FaceDetector;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;
public class MainActivity extends Activity{
 private ImageView preview;private Bitmap original,result;private SeekBar brightness,smooth;private static final int PICK=10,CAMERA=11,CAM_PERMISSION=12;
 @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();}
 private TextView text(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setPadding(16,10,16,10);return t;}private Button button(String s){Button b=new Button(this);b.setText(s);return b;}
 private void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);TextView title=text("Sanchit Passport Photo",24);title.setGravity(Gravity.CENTER);root.addView(title);root.addView(text("Face-aware Auto Crop • Camera / Gallery • बिना AI",14));preview=new ImageView(this);preview.setBackgroundColor(Color.rgb(230,230,230));preview.setScaleType(ImageView.ScaleType.FIT_CENTER);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));LinearLayout source=new LinearLayout(this);Button camera=button("📷 कैमरा");Button pick=button("🖼 फोटो चुनें");source.addView(camera,new LinearLayout.LayoutParams(0,-2,1));source.addView(pick,new LinearLayout.LayoutParams(0,-2,1));root.addView(source);camera.setOnClickListener(v->openCamera());pick.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_PICK,MediaStore.Images.Media.EXTERNAL_CONTENT_URI),PICK));root.addView(text("Fairness / Brightness",14));brightness=new SeekBar(this);brightness.setMax(80);brightness.setProgress(24);root.addView(brightness);root.addView(text("Smooth",14));smooth=new SeekBar(this);smooth.setMax(4);smooth.setProgress(1);root.addView(smooth);LinearLayout row=new LinearLayout(this);Button process=button("फिर से Process");Button reset=button("RESET");row.addView(process,new LinearLayout.LayoutParams(0,-2,1));row.addView(reset,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);process.setOnClickListener(v->process());reset.setOnClickListener(v->reset());Button save=button("फोटो सेव करें");root.addView(save);save.setOnClickListener(v->save());setContentView(root);}
 private void openCamera(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.CAMERA")!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{"android.permission.CAMERA"},CAM_PERMISSION);return;}Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);if(i.resolveActivity(getPackageManager())!=null)startActivityForResult(i,CAMERA);else toast("Camera उपलब्ध नहीं है");}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==CAM_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)openCamera();else if(r==CAM_PERMISSION)toast("Camera permission जरूरी है");}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);try{if(c!=RESULT_OK)return;if(r==PICK&&d!=null){original=MediaStore.Images.Media.getBitmap(getContentResolver(),d.getData());auto();}else if(r==CAMERA&&d!=null&&d.getExtras()!=null){Object o=d.getExtras().get("data");if(o instanceof Bitmap){original=(Bitmap)o;auto();}}}catch(Exception e){toast("Photo error: "+e.getMessage());}}
 private void auto(){brightness.setProgress(24);smooth.setProgress(1);process();}
 private void reset(){result=null;original=null;preview.setImageDrawable(null);brightness.setProgress(24);smooth.setProgress(1);toast("Reset हो गया — नई फोटो चुनें");}
 private void process(){if(original==null){toast("पहले फोटो लें या चुनें");return;}Bitmap crop=smartCrop(original);int w=700,h=900;Bitmap src=Bitmap.createScaledBitmap(crop,w,h,true),out=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);int add=brightness.getProgress(),rad=smooth.getProgress();int[] p=new int[w*h];src.getPixels(p,0,w,0,0,w,h);int[] corners={p[0],p[w-1],p[(h-1)*w],p[h*w-1]};int br=0,bg=0,bb=0;for(int cc:corners){br+=Color.red(cc);bg+=Color.green(cc);bb+=Color.blue(cc);}br/=4;bg/=4;bb/=4;for(int i=0;i<p.length;i++){int cc=p[i],rr=Color.red(cc),gg=Color.green(cc),bl=Color.blue(cc),dr=rr-br,dg=gg-bg,db=bl-bb;double dist=Math.sqrt(dr*dr+dg*dg+db*db);boolean back=dist<58||(rr>210&&gg>210&&bl>210)||(gg>rr*1.20&&gg>bl*1.16&&gg>75);if(back){p[i]=Color.rgb(74,144,194);continue;}rr=Math.min(255,(int)(rr*1.035)+add);gg=Math.min(255,(int)(gg*1.035)+add);bl=Math.min(255,(int)(bl*1.025)+add);p[i]=Color.rgb(rr,gg,bl);}out.setPixels(p,0,w,0,0,w,h);if(rad>0)for(int n=0;n<rad;n++)out=boxBlur(out);result=out;preview.setImageBitmap(result);toast("Face-aware Auto Crop तैयार");}
 // Built-in classical Android FaceDetector: no ML/AI dependency. Uses eye midpoint + eye distance to position a 7:9 ID crop.
 private Bitmap smartCrop(Bitmap b){try{int ow=b.getWidth(),oh=b.getHeight();int dw=Math.min(1000,ow);float scale=(float)dw/ow;int dh=Math.max(2,(int)(oh*scale));if((dw&1)==1)dw--;Bitmap small=Bitmap.createScaledBitmap(b,dw,dh,true).copy(Bitmap.Config.RGB_565,false);FaceDetector fd=new FaceDetector(small.getWidth(),small.getHeight(),1);FaceDetector.Face[] fs=new FaceDetector.Face[1];if(fd.findFaces(small,fs)>0&&fs[0]!=null){PointF m=new PointF();fs[0].getMidPoint(m);float inv=(float)ow/small.getWidth(),cx=m.x*inv,eyesY=m.y*inv,eye=fs[0].eyesDistance()*inv;float cw=eye*5.2f;cw=Math.max(cw,ow*0.34f);cw=Math.min(cw,ow);float ch=cw*9f/7f;if(ch>oh){ch=oh;cw=ch*7f/9f;}float desiredEyes=ch*0.39f;float left=cx-cw/2f,top=eyesY-desiredEyes;left=Math.max(0,Math.min(left,ow-cw));top=Math.max(0,Math.min(top,oh-ch));int x=Math.round(left),y=Math.round(top),w=Math.max(1,Math.min(Math.round(cw),ow-x)),h=Math.max(1,Math.min(Math.round(ch),oh-y));float ratio=(float)w/h;if(ratio>7f/9f)w=Math.round(h*7f/9f);else if(ratio<7f/9f)h=Math.round(w*9f/7f);return Bitmap.createBitmap(b,x,y,w,h);}}catch(Exception ignored){}return crop79(b);}
 private Bitmap crop79(Bitmap b){int w=b.getWidth(),h=b.getHeight();float t=7f/9f;int nw=w,nh=h;if((float)w/h>t)nw=(int)(h*t);else nh=(int)(w/t);return Bitmap.createBitmap(b,(w-nw)/2,(h-nh)/2,nw,nh);}
 private Bitmap boxBlur(Bitmap s){int w=s.getWidth(),h=s.getHeight();Bitmap d=s.copy(Bitmap.Config.ARGB_8888,true);int[] a=new int[w*h],o=new int[w*h];s.getPixels(a,0,w,0,0,w,h);System.arraycopy(a,0,o,0,a.length);for(int y=1;y<h-1;y+=2)for(int x=1;x<w-1;x+=2){long rr=0,gg=0,bb=0;for(int yy=-1;yy<=1;yy++)for(int xx=-1;xx<=1;xx++){int c=a[(y+yy)*w+x+xx];rr+=Color.red(c);gg+=Color.green(c);bb+=Color.blue(c);}o[y*w+x]=Color.rgb((int)(rr/9),(int)(gg/9),(int)(bb/9));}d.setPixels(o,0,w,0,0,w,h);return d;}
 private void save(){if(result==null){toast("पहले फोटो तैयार करें");return;}try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"Sanchit_Passport_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Sanchit Passport Photo");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);OutputStream os=getContentResolver().openOutputStream(u);result.compress(Bitmap.CompressFormat.JPEG,96,os);os.close();toast("फोटो सेव हो गई");}catch(Exception e){toast("Save error: "+e.getMessage());}}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}